### ISSUE TITLE
not a problem report, but why am I not getting back the frame I send

### ISSUE THREAD

**Issue by saraf** [yope/linux-j1939-testing#2]
What could be the reason that I am not getting back a frame sent to a loopback vcan device?

```
$ python3 ./test_provt.py vcan32
Send address claimed = 128
Traceback (most recent call last):
  File "./test_provt.py", line 95, in <module>
    t.run()
  File "./test_provt.py", line 87, in run
    self.loop.run_until_complete(self.run_coro())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "./test_provt.py", line 76, in run_coro
    await self.test_frame()
  File "./test_provt.py", line 65, in test_frame
    assert(ret is not None)
AssertionError
```

While - using candump - I can see -
```
 vcan32  18EEFF80   [8]  FF FF 9F 34 00 1D 00 80
  vcan32  18EEFF80   [8]  FF FF 9F 34 00 1D 00 80
  vcan32  18EAFF80   [3]  00 EE 00
  vcan32  18EAFF80   [3]  00 EE 00
  vcan32  18E72680   [8]  C0 FF 03 04 05 06 FF FF
  vcan32  18E72680   [8]  C0 FF 03 04 05 06 FF FF
```

**Comment by yope** [comment]
Hi @saraf . Sorry for responding so late. This tool is not supposed to be used with a loopback device. The idea of this tool is to test the upcoming J1939 kernel stack. It contains a minimal J1939 user-space implementation and should talk to an IsoBus virtual terminal (or similar) running on the J1939 kernel stack.
I should take some time to write documentation for it...
